services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5433:5432"
    networks:
      - my-net

  mysql8:
    container_name: mysql
    image: mysql:8.1
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    - MYSQL_ROOT_HOST=%
    restart: always
    ports:
    - "3307:3306"
    networks:
    - my-net

  mongo:
    image: mongo:6.0.8
    container_name: mongo
    restart: always
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    networks:
    - my-net

networks:
  my-net:
    name: my-net
